### PR TITLE
upgrade to asp.net core rc2

### PR DESCRIPTION
**Pull request by mkjeff**
Migrated to asp.net core rc2. working on Dnx.

testing framework's packages could not resolve.

Dnx will be replaced by .NetCore(CLI), not release yet(visual studio does not support too). 
This should be a temporary version. Hope the next version without too many changes

### CODE REVIEW

**Comment by Ciantic** [comment]
Looks like this is already outdated, there is ApiDescription seems to have changes.

**Comment by BearTM** [comment]
I've only updated Swashbuckle.SwaggerGen/SwaggerUi to have it working under 1.0.0-rc3-20541

Apologies no time to create a separate Pull, but here are the changes I've made:
(NOTE: Using dotnet to compile/run/publish)

project.json
```
  "dependencies": {
    "Microsoft.AspNetCore.Mvc": "1.0.0-rc3-20541",
    "Microsoft.AspNetCore.Mvc.ApiExplorer": "1.0.0-rc3-20541",
    "Microsoft.AspNetCore.Mvc.Dnx": "1.0.0-rc3-20541",
    "Microsoft.AspNetCore.Mvc.Razor": "1.0.0-rc3-20541"
  },
  "frameworks": {
    "net451": {
      "frameworkAssemblies": {
        "System.Collections": { "type": "build" },
        "System.ComponentModel": { "type": "build" },
        "System.Reflection": { "type": "build" },
        "System.Runtime": { "type": "build" },
        "System.Web": { "type": "build" }
      }
    }
  },
```

**From master: Change references from AspNet to AspNetCore for both usings and namespaces:**

**SwaggerGen:**
- XmlCommentsOperationFilter.cs
- SwaggerApplicationConvention.cs
- SwaggerGenBuilderExtensions.cs
- SwaggerGenOptions.cs
- SwaggerGenServiceCollectionExtensions.cs
- ApiDescriptionExtensions.cs
- IDocumentFilter.cs
- IOperationFilter.cs
- SchemaRegistry.cs
- SwaggerProvider.cs
- SwaggerProviderOptions.cs

**SwaggerUi:**
- RedirectMiddleware.cs
- SwaggerUiBuilderExtensions.cs
- SwaggerUiMiddleware.cs

i.e. change everywhere:
```
using Microsoft.AspNet.Mvc.Controllers;
namespace Microsoft.AspNet.Builder;
using Microsoft.Extensions.OptionsModel;
```

to:
```
using Microsoft.AspNetCore.Mvc.Controllers;
namespace Microsoft.AspNetCore.Builder;
using Microsoft.Extensions.Options;
```

**Code changes needed in SwaggerGen:**

SwaggerGenMiddleware.cs
```
        private bool RequestingSwaggerDocs(HttpRequest request, out string apiVersion)
        {
            apiVersion = null;
            if (request.Method != "GET") return false;

            // var routeValues = _requestMatcher.Match(request.Path);
            // if (routeValues == null || !routeValues.ContainsKey("apiVersion")) return false;

            var routeValues = new RouteValueDictionary();
            if (!_requestMatcher.TryMatch(request.Path, routeValues)) return false;
            if (!routeValues.ContainsKey("apiVersion")) return false;
            apiVersion = routeValues["apiVersion"].ToString();
            return true;
        }
```

ApiDescriptionExtensions.cs
```
        public static IEnumerable<string> Produces(this ApiDescription apiDescription)
        {
            return apiDescription.SupportedResponseTypes
                .SelectMany(responseType => responseType.ApiResponseFormats)
                .Select(responseFormat => responseFormat.MediaType)
                .Distinct();

            //return apiDescription.SupportedResponseFormats
            //    .Select(format => format.MediaType);
        }
```

SchemaRegistry.cs
```
        private Schema CreateDictionarySchema(JsonDictionaryContract dictionaryContract)
        {
            var keyType = dictionaryContract.DictionaryKeyType ?? typeof(object);
            var valueType = dictionaryContract.DictionaryValueType ?? typeof(object);

            if (keyType.GetTypeInfo().IsEnum)
            {
                return new Schema
                {
                    Type = "object",
                    Properties = Enum.GetNames(keyType).ToDictionary(
                        // (name) => dictionaryContract.PropertyNameResolver(name),
                        (name) => dictionaryContract.DictionaryKeyResolver(name),
                        (name) => CreateInlineSchema(valueType)
                    )
                };
            }
            else
            {
                return new Schema
                {
                    Type = "object",
                    AdditionalProperties = CreateInlineSchema(valueType)
                };
            }
        }
```

SwaggerProvider.cs
```
        private Operation CreateOperation(ApiDescription apiDescription, ISchemaRegistry schemaRegistry)
        {
            var groupName = _options.GroupNameSelector(apiDescription);

            var parameters = apiDescription.ParameterDescriptions
                .Where(paramDesc => paramDesc.Source.IsFromRequest)
                .Select(paramDesc => CreateParameter(paramDesc, schemaRegistry))
                .ToList();

            var responses = new Dictionary<string, Response>();

            //if (apiDescription.ResponseType == typeof(void))
            //    responses.Add("204", new Response { Description = "No Content" });
            //else
            //    responses.Add("200", CreateSuccessResponse(apiDescription.ResponseType, schemaRegistry));

            var responseTypes = apiDescription.SupportedResponseTypes.Select(responseType => responseType.Type);
            foreach (var responseType in responseTypes)
            {
              if (responseType == typeof(void))
                  responses.Add("204", new Response { Description = "No Content" });
              else
                  responses.Add("200", CreateSuccessResponse(responseType, schemaRegistry));
            }

            var operation = new Operation
            {
                Tags = (groupName != null) ? new[] { groupName } : null,
                OperationId = apiDescription.FriendlyId(),
                Produces = apiDescription.Produces().ToList(),
                //consumes = apiDescription.Consumes().ToList(),
                Parameters = parameters.Any() ? parameters : null, // parameters can be null but not empty
                Responses = responses,
                Deprecated = apiDescription.IsObsolete()
            };

            var filterContext = new OperationFilterContext(apiDescription, schemaRegistry);
            foreach (var filter in _options.OperationFilters)
            {
                filter.Apply(operation, filterContext);
            }

            return operation;
        }
```

**Comment by Ciantic** [comment]
@BearTM I attempted with this pr, and with your instructions, one problem what is the "CreateInlineSchema"? It's not defined.

**Comment by BearTM** [comment]
CreateInlineSchema is a function in the same file (SchemaRegistry.cs) ...it's there in master.
In the code snippets above, just match/replace the code where I'd made the changes. Should be easy to spot. :)
`private Schema CreateInlineSchema(Type type)`

**Comment by domaindrivendev** [comment]
Looking at the various PR's, it looks like a lot of people are duplicating work - I also have a local RC2 branch in progress. My bad for lack of communication. With two small kids there just aint enough hours in the day - even to just get the appropriate communication out there :(

I won't be accepting any PR's that don't come with a green suite of tests so that makes #88 the likely candidate. I'm going to pull it down tomorrow and compare with my own local branch before merging one of them into master. Either way, I'm targeting 5/28 for an RC2 compatible release to Nuget. See the beta2 milestone here https://github.com/domaindrivendev/Ahoy/milestones. Note the revert to "beta" status - still lots of feature gaps and a config. API that will likely undergo change before we reach a stable release.

Thanks to everyone for chipping in. Please don't get disheartened if I'm slow to respond to PR's. So long as they include tests and a passing suite, I'll get always consider them and strive to respond as soon as I can.

I have one significant architectural refactor that I want to get done after the beta2 release. After this, I'll be looking to open up the project and add additional contributors. For anyone reading this, please let me know if you're interested?

Ahoy!

Richie

**Pull request closed without merging**
