### PR TITLE
Updated to work with -rc1-final

### PR DESCRIPTION
**Pull request by vapidsquid**
* Changed Microsoft.Framework namespaces to Microsoft.Extensions
* Template matching now uses PathString instead of string
* Updated xunit DNX Runner to use -rc1-*
* Updated version numbers to -rc1-final

### CODE REVIEW

**Comment by mcliment** [comment]
:+1:

**Comment by kjartanvalur** [comment]
Well done!!

**Comment by senj** [comment]
Nuget?

**Comment by ankitbko** [comment]
When will the nuget be released?

**Pull request merged**
