### PR TITLE
Updated for rc2-final

### PR DESCRIPTION
**Pull request by senwen**
Got it working with rc2-final (dnx -> dotnet) based on work started by BearTM. 

Hope this helps others.

Ps, I did not touch the test project.

### CODE REVIEW

**Comment by xperiandri** [comment]
You have not changed targets
[See](https://wildermuth.com/2016/05/17/Converting-an-ASP-NET-Core-RC1-Project-to-RC2)

**Comment by senwen** [comment]
@xperiandri what are you referring to ..my pull request? My changes are working fine and framework project.json was updated. I submitted a pull request in case owner wants to merge in.

**Comment by domaindrivendev** [comment]
Looking at the various PR's, it looks like a lot of people are duplicating work - I also have a local RC2 branch in progress. My bad for lack of communication. With two small kids there just aint enough hours in the day - even to just get the appropriate communication out there :(

I won't be accepting any PR's that don't come with a green suite of tests so that makes #88 the likely candidate. I'm going to pull it down tomorrow and compare with my own local branch before merging one of them into master. Either way, I'm targeting 5/28 for an RC2 compatible release to Nuget. See the beta2 milestone here https://github.com/domaindrivendev/Ahoy/milestones. Note the revert to "beta" status - still lots of feature gaps and a config. API that will likely undergo change before we reach a stable release.

Thanks to everyone for chipping in. Please don't get disheartened if I'm slow to respond to PR's. So long as they include tests and a passing suite, I'll get always consider them and strive to respond as soon as I can.

I have one significant architectural refactor that I want to get done after the beta2 release. After this, I'll be looking to open up the project and add additional contributors. For anyone reading this, please let me know if you're interested?

Ahoy!

Richie

**Comment by senwen** [comment]
@domaindrivendev, 
No worries and that makes sense.
Thanks for your contributions.

**Comment by jacksontbryan** [comment]
Im willing to contribute.

**Pull request closed without merging**
