### PR TITLE
converted to dotnetcore 1.0

### PR DESCRIPTION
**Pull request by mihevc**
Updated to core 1.0 and tooling preview 2.  I hope this is helpful.

### CODE REVIEW

**Comment by AlexCuse** [comment]
I was about to look into this myself.  Would be happy to help with testing or any remaining work.

**Comment by AlexCuse** [comment]
@mihevc have you tried this at all?  We are finding a lot of breaking changes to json serialization in the move to 1.0, thinking about pushing a temporary package to nuget so we can use the UI to work through them.

**Comment by mihevc** [comment]
The only issues I ran into with serialization that now they camel case json by default and they changed up the constructors a bit.  I was able to work around them.  The constructor one caused me more issues.

**Comment by domaindrivendev** [comment]
The original PR for this - #112 has already been merged in.

**Comment by AlexCuse** [comment]
Ah great, thank you!

**Pull request closed without merging**
