### PR TITLE
Updated to beta8

### LINKED ISSUE #25: Swashbuckle doesn't work with ASP.NET 5.0 on beta8

### PR DESCRIPTION
**Pull request by mcliment**
Updated to beta8 which should close #25 now that beta8 is released.
I have not pushed project.json.lock files because I'm not sure it they should be commited.

### CODE REVIEW

**Comment by mcliment** [comment]
I've already changed the dependency.

**Comment by anwalkers** [comment]
+1 I pulled the branch down and integrated it with a project. Worked great.

**Comment by sandorfr** [comment]
Thanks, gonna save me time :)

**Comment by kirk-marple** [comment]
Naive question, what's the typical ETA to get this pull request integrated into a release?

I have a project which I had to pull Swashbuckle from, until this was ready, and hoping to re-integrate it ASAP.

**Comment by mcliment** [comment]
You're welcome. :tada:

**Comment by mcliment** [comment]
I added this last change to make samples work out of the box on IISExpress which is the default option in VS2015.

**Comment by mcliment** [comment]
And finally a small change for those who want to check the samples under OSX/Linux.

**Comment by sandorfr** [comment]
Just in case someone needs it, I uploaded the nuget packages there : https://www.myget.org/F/sandor-public/api/v3/index.json

**Comment by domaindrivendev** [comment]
Great contribution thx. I'm just in the process of getting the nugets pushed

**Comment by mcliment** [comment]
:clap: :clap: :clap:

**Comment by kirk-marple** [comment]
Curious, is there something blocking this release for beta8?  We're eager to get this re-integrated back into our DNX project, and would prefer to use the official nuget package.  Thanks!

**Comment by domaindrivendev** [comment]
Two things delaying this ...

1) The job which actually pays the bills :)
2) I was having issues running the sample apps locally

The latter is sorted now so will try find the time to release later.

Actually there is minor annoyance I'm facing and would like to get everyone's opinion. Since the last release, I've broken down into two projects - Swashbuckle.Swagger and Swashbuckle.SwaggerUi. The latter adds the embedded swagger-ui to consume the Swagger produced by the former. I want to push both as packages but continue to use package id "Swashbuckle" for the SwaggerUi project, as it encapsulates the complete functionality people have come to expect from Swashbuckle - e.g. Swagger JSON AND the embedded swagger-ui.

The problem is "dnu pack" uses the folder name as the package name and I can't find any way to override this. So, it seems my options are as follows:

1) Rename the Swashbuckle.SwaggerUi project to just Swashbuckle
2) Move away from the package name "Swashbuckle" and point people to Swashbuckle.SwaggerUi if they want the complete bundle.

Thoughts?

**Comment by kirk-marple** [comment]
Thanks for the reply, totally understand about issue #1 :)

Personally, I'm fine with this option:

>> 1) Rename the Swashbuckle.SwaggerUi project to just Swashbuckle

Do you find many people use the core Swagger without UI?


On Wed, Oct 28, 2015 at 1:07 PM, domaindrivendev <notifications@github.com>
wrote:

> Two things delaying this ...
>
> 1) The job which actually pays the bills :)
> 2) I was having issues running the sample apps locally
>
> The latter is sorted now so will try find the time to release later.
>
> Actually there is minor annoyance I'm facing and would like to get
> everyone's opinion. Since the last release, I've broken down into two
> projects - Swashbuckle.Swagger and Swashbuckle.SwaggerUi. The latter adds
> the embedded swagger-ui to consume the Swagger produced by the former. I
> want to push both as packages but continue to use package id "Swashbuckle"
> for the SwaggerUi project, as it encapsulates the complete functionality
> people have come to expect from Swashbuckle - e.g. Swagger JSON AND the
> embedded swagger-ui.
>
> The problem is "dnu pack" uses the folder name as the package name and I
> can't find any way to override this. So, it seems my options are as follows:
>
> 1) Rename the Swashbuckle.SwaggerUi project to just Swashbuckle
> 2) Move away from the package name "Swashbuckle" and point people to
> Swashbuckle.SwaggerUi if they want the complete bundle.
>
> Thoughts?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/domaindrivendev/Ahoy/pull/31#issuecomment-151975141>.
>



-- 
*​KIRK MARPLE* | Candela Software Technologies, LLC | Direct: 206.660.6676 |
Skype: kirkmarple | Email: kirk@candela.software

**Comment by mcliment** [comment]
Which bills? Isn't GitHub free? :stuck_out_tongue_winking_eye: 

Option 1 seems OK, it'll solve the problem.

Other option may be an "empty" Swashbuckle project that depends on both .Swagger and .SwaggerUI that will act as a transitional package.

**Comment by tdekoekkoek** [comment]
Could someone please tell me the steps to get this to work until nuget is updated.  I've just upgraded my project to beta8 and am a little lost.  Thanks!

**Comment by domaindrivendev** [comment]
Hey all - I finally got around to publishing the beta8 compatible Nuget. The following should work in a beta8 application:

    Install-Package Swashbuckle -Version 6.0.0-beta8 -Pre

Let me know if there's any issues

**Comment by rynowak** [comment]
:clap: thanks!

**Comment by tdekoekkoek** [comment]
Here I am in github looking for the "Like" button ;)  Thanks!

**Comment by kirk-marple** [comment]
Much appreciated, thanks!

**Comment by tdekoekkoek** [comment]
I'm getting the following:

Install-Package : Package stream for 'Swashbuckle.6.0.0-beta8' cannot be found at 
'https://www.nuget.org/api/v2/curated-feeds/microsoftdotnet/'.

Any ideas?

**Comment by ifergus** [comment]
Note that there is more that one "Package Source."  You might need to change the source drop-down to "api.nuget.org" if you don't find the package under "Microsoft and .NET"

**Pull request merged**
